### ISSUE TITLE
Merge downvoting and upvoting into the same PUT

### ISSUE THREAD

**Issue by joshuapj** [The-Grasshoppers/DRSS-comp3613-a1#5]
https://github.com/The-Grasshoppers/DRSS-comp3613-a1/blob/8ca69e3b12202064425a645738662b1a753686b8/App/views/review.py#L46-L65

Downvoting/Upvoting a review can be the same PUT to /review/id with the desired action given in the body

**Comment by LYS312** [comment]
![image](https://user-images.githubusercontent.com/101906986/205421973-50ff5a06-553b-4997-a054-34ebacd4c453.png)
